compact: true
directory:
- gcp-gke
download-external-modules: true
evaluate-variables: true
external-modules-download-path: .external_modules
framework:
- all
quiet: true
skip-path:
  - .external_modules
  - modules
skip-check:
  # Need to skip this because it wants to prevent us from destroying the KMS but
  # the terratest need to be able to destroy it
  - CKV_GCP_82
